name: "Validate HTML"

on:
  pull_request:
    types: [opened, reopened, edited]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: /
        blacklist: usr/local/lib/python3.12/*
        format: text
        css: true 
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log